---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    ports:
      - "9092:9092"
      # - "9999:9999"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.21.0.115:9092
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 3
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 #3
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      # KAFKA_JMX_OPTS: -Djava.rmi.server.hostname=10.21.0.115 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      # KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9999:/opt/kafka.yml"
      # EXTRA_ARGS: -javaagent:./jmx_prometheus_javaagent-0.18.0.jar=9999:./kafka.yml
      # JMX_PORT: 1099
      # KAFKA_MESSAGE_MAX_BYTES: 2000000000
    # volumes:
    #   - ./jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
    #   - ./kafka.yml:/opt/kafka.yml

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # kafka-connect:
  #   image: confluentinc/cp-kafka-connect
  #   container_name: kafka-connect
  #   ports:
  #     - "8083:8083"
  #     - "9996:9996"
  #   depends_on:
  #     - zookeeper
  #     - kafka1
  #     - kafka2
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: 10.21.0.115:9092
  #     CONNECT_GROUP_ID: connect-cluster
  #     CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #     CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #     CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: true
  #     CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: true
  #     CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3 #3
  #     CONNECT_OFFSET_STORAGE_PARTITIONS: 25
  #     CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3 #3
  #     CONNECT_STATUS_STORAGE_TOPIC: connect-status
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3 #3
  #     CONNECT_STATUS_STORAGE_PARTITIONS: 5
  #     CONNECT_OFFSET_FLUSH_INTERVAL_MS: 60000
  #     # CONNECT_LISTENERS: http://:8083
  #     CONNECT_REST_ADVERTISED_HOST_NAME: 10.21.0.115
  #     CONNECT_REST_ADVERTISED_PORT: 8083
  #     # CONNECT_REST_ADVERTISED_LISTENER:
  #     CONNECT_PLUGIN_PATH: /usr/share/java/kafka
  #     KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9996:/opt/kafka.yml"
  #   volumes:
  #     - ./connect:/usr/share/java/kafka
  #     - ./jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
  #     - ./kafka.yml:/opt/kafka.yml

  # kafka2:
  #   image: confluentinc/cp-kafka
  #   container_name: kafka2
  #   ports:
  #     - "9093:9093"
  #     - "9998:9998"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.21.0.115:9093
  #     KAFKA_NUM_NETWORK_THREADS: 3
  #     KAFKA_NUM_IO_THREADS: 3
  #     KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
  #     KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
  #     KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
  #     KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
  #     KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
  #     KAFKA_LOG_RETENTION_HOURS: 168
  #     KAFKA_LOG_RETENTION_BYTES: 1073741824
  #     KAFKA_LOG_SEGMENT_BYTES: 1073741824
  #     KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
  #     KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9998:/opt/kafka.yml"
  #   volumes:
  #     - ./jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
  #     - ./kafka.yml:/opt/kafka.yml

  # kafka3:
  #   image: confluentinc/cp-kafka
  #   container_name: kafka3
  #   ports:
  #     - "9094:9094"
  #     - "9997:9997"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.21.0.115:9094
  #     KAFKA_NUM_NETWORK_THREADS: 3
  #     KAFKA_NUM_IO_THREADS: 3
  #     KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
  #     KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
  #     KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
  #     KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
  #     KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
  #     KAFKA_LOG_RETENTION_HOURS: 168
  #     KAFKA_LOG_RETENTION_BYTES: 1073741824
  #     KAFKA_LOG_SEGMENT_BYTES: 1073741824
  #     KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
  #     KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9997:/opt/kafka.yml"
  #   volumes:
  #     - ./jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
  #     - ./kafka.yml:/opt/kafka.yml

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center
  #   container_name: control-center
  #   ports:
  #     - "9021:9021"
  #   depends_on:
  #     - zookeeper
  #     - kafka1
  #     - kafka2
  #     - kafka3
  #     - kafka-connect
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: '10.21.0.115:9092,10.21.0.115:9093,10.21.0.115:9094' 
  #     CONTROL_CENTER_ZOOKEEPER_CONNECT: '10.21.0.115:2181' 
  #     CONTROL_CENTER_CONNECT_CONNECT_CLUSTER: 'http://10.21.0.115:8083'
  #     CONTROL_CENTER_KAFKA_CLUSTER_ID: 1
  #     CONTROL_CENTER_REPLICATION_FACTOR: 3