---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9999:9999"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.77:9092
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 1024000
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 1024000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 #3
      # KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      # KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_HOURS: 168
      # KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824 2147483647 2,147,483,647
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
    #   KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9999:/opt/kafka.yml"
      KAFKA_HEAP_OPTS: "-Xmx4g"
    # volumes:
    #   - ./jmx/jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
    #   - ./jmx/kafka.yml:/opt/kafka.yml

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9191"
  #   depends_on:
  #     - kafka-connect
  #   volumes:
  #     - ./jmx/prometheus.yml:/etc/prometheus/prometheus.yml
    
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on: 
  #     - prometheus

  kafka-connect:
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect
    ports:
      - "22028:22028"
      - "9998:9998"
    depends_on:
      - kafka1
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 192.168.0.77:9092
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: true
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: true
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1 #3
      # CONNECT_OFFSET_STORAGE_PARTITIONS: 25
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1 #3
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1 #3
      # CONNECT_STATUS_STORAGE_PARTITIONS: 5
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 60000
      CONNECT_LISTENERS: http://:22028
      CONNECT_REST_ADVERTISED_HOST_NAME: 192.168.0.77
      CONNECT_REST_ADVERTISED_PORT: 22028
      # CONNECT_REST_ADVERTISED_LISTENER: http://:22028
      CONNECT_PLUGIN_PATH: /usr/share/java/kafka
      # KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.18.0.jar=9998:/opt/kafka.yml"
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx6g"
    volumes:
      - ./connect:/usr/share/java/kafka
      # - ./jmx/jmx_prometheus_javaagent-0.18.0.jar:/opt/jmx_prometheus_javaagent-0.18.0.jar
      # - ./jmx/kafka.yml:/opt/kafka.yml
      # - ./csv-test:/opt/csv-test
